import React from "react";
import {
    AppLogo,
    HomeHeaderMask,
    MenuIcon,
    SearchIcon,
    Location,
    Document,
    ClockIcon,
    ProfileIcon,
    ProfileMask,
    CrossIcon,
    RefreshIcon,
    FilterIcon,
    BackIcon,
    LoginScreenLogo,

    PasswordLock,
    EmailIcon,
    CameraIcon,
    LocationMarker,
    LeftArrowIcon,
    RightArrowIcon,
    EyeIcon,
    EyeSlashIcon,
    BidIcon,
    HeartIcon,
    ShareIcon,
    EditIcon,
    DeleteIcon,
    CheckedCheckboxIcon, UncheckedCheckboxIcon,
    UserIcon,
    ProfileEditIcon,
    ExpireIcon,
    CalenderIcon
} from './Icon';



export const Icons = {
    AppLogo,
    HomeHeaderMask,
    MenuIcon,
    SearchIcon,
    Location,
    Document,
    ClockIcon,
    ProfileIcon,
    ProfileMask,
    CrossIcon,
    RefreshIcon,
    FilterIcon,
    BackIcon,
    LoginScreenLogo,

    PasswordLock,
    EmailIcon,
    CameraIcon,
    LocationMarker,
    LeftArrowIcon,
    RightArrowIcon,
    EyeIcon,
    EyeSlashIcon,
    BidIcon,
    HeartIcon,
    ShareIcon,
    EditIcon,
    DeleteIcon,
    CheckedCheckboxIcon, UncheckedCheckboxIcon,
    UserIcon,
    ProfileEditIcon,
    ExpireIcon,
    CalenderIcon
}