export const Types = {
    SETAPPSTATUS: "SETAPPSTATUS",
    SET_SPINNER: "SET_SPINNER",
    SET_APP_LANG: "SET_APP_LANG",
    SET_DASHBOARD_DATA: "SET_DASHBOARD_DATA",
    SET_FILTER_OPTIONS: "SET_FILTER_OPTIONS",
    SET_USER_IMAGE: "SET_USER_IMAGE",
    LOGOUT: "LOGOUT",
}